name: Update Cache

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install packages
        run: |
          npm install --only=dev
          npm install

      - name: Update cache
        run: npm run cache

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: Update cache from Google Sheet

      - name: Build app
        run: npm run build
        env:
          CI: true
          NODE_ENV: production
          DATE: ${{ date -u +"%Y-%m-%dT%H:%M:%SZ" }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
